### ISSUE TITLE
Change order of icons

### ISSUE THREAD

**Issue by AsaiToshiya** [AsaiToshiya/n#16]
Swap the order of the new icon and the list icon.

**Comment by Aspireve** [comment]
Hey @AsaiToshiya  Could I do this?

**Comment by AsaiToshiya** [comment]
Hi @Aspireve, yes you can do that.

**Comment by Aspireve** [comment]
Hey @AsaiToshiya I made the changes and made the pull request, do review it.
Thanks!!

**Comment by AsaiToshiya** [comment]
Thank you for the contribution.
