### ISSUE TITLE
Fix deselecting note

### ISSUE THREAD

**Issue by Saeed-Paris** [AsaiToshiya/n#19]
Cannot read properties of undefined (reading 'text')
Cannot read properties of null (reading 'focus')
somehow after clicking some buttons i got these errors

**Comment by AsaiToshiya** [comment]
Thank you for the bug report @Saeed-Paris.

Could you please tell me which browser and version you are using.

**Comment by Saeed-Paris** [comment]
@AsaiToshiya i dont think that browser and version matter.
but if u want  i used 
chrome
Version 103.0.5060.134 (Official Build) (64-bit)

**Comment by AsaiToshiya** [comment]
That is one of the possibilities.

This problem occurs when deselecting a note ~~using ctrl-click~~.

I will fix it.

**Comment by AsaiToshiya** [comment]
Fixed so that a note cannot be deselected.

Thank you @Saeed-Paris.
