### ISSUE TITLE
Do not add new note if top of note list is empty note

### ISSUE THREAD

**Issue by AsaiToshiya** [AsaiToshiya/n#20]

**Comment by Aspireve** [comment]
Hey @AsaiToshiya could I do this?

**Comment by Aspireve** [comment]
Hey @AsaiToshiya I made the program and it works something like this is this fine.
![N - Google Chrome 2022-07-26 19-15-34](https://user-images.githubusercontent.com/93852415/181022419-f3fac386-363f-4683-8894-794921b67517.gif)
P.S. I added the alert option to show that there is an empty file before,
Should I push it with the alert or should I implement something along with it

**Comment by AsaiToshiya** [comment]
Thank you @Aspireve.

The alert is not required. Instead, please focus on the textarea.

**Comment by Aspireve** [comment]
Yup I'll do that and make the pull request quick
