### ISSUE TITLE
Do not display "Empty" in note list

### ISSUE THREAD

**Issue by AsaiToshiya** [AsaiToshiya/n#55]

**Comment by lmash12** [comment]
hi. I would like to help out with this. what would you like to be displayed?

**Comment by AsaiToshiya** [comment]
No need to display anything.

In other words, display an empty string ("") instead of "Empty".

**Comment by lmash12** [comment]
alright, I would love to have a go at it.

**Comment by lmash12** [comment]
you're welcome. thank you for the opportunity.
